(() => {
  const gameDefaults = {
    type: "Игра", recommendation: "A", priority: "A", status: "Не пробовал",
    impression: "—", buy: "Не решил", story: "Есть", multiplayer: "Нет",
    comfort: "Средний риск", basePrice: null, currentPrice: null, discount: null,
    purchasePrice: null, comment: "", source: "", installWhere: "Quest", qloader: "проверить"
  };
  const programDefaults = {
    type: "Программа", recommendation: "—", priority: "A", status: "Не пробовал",
    impression: "—", buy: "Не решил", story: "—", multiplayer: "—", comfort: "—",
    basePrice: null, currentPrice: null, discount: null, purchasePrice: null,
    comment: "", availability: "Программа", best: "—", bestRaw: "—", qloader: "—"
  };
  const adultDefaults = {
    type: "18+", category: "18+", recommendation: "A", priority: "A", status: "Не пробовал",
    impression: "—", buy: "Не решил", story: "—", multiplayer: "Нет", comfort: "Средний риск",
    basePrice: null, currentPrice: null, discount: null, purchasePrice: null,
    comment: "", best: "Равно / по ситуации", qloader: "проверить"
  };

  const acceptedMissing = [
    {id:"curated-001",name:"Arken Age",category:"Сюжет",subcategory:"Sci-fi / экшен-приключение",availability:"Meta + Steam",best:"Steam лучше",platform:"Quest 3 + PCVR",bestRaw:"PCVR для графики; Quest 3 для автономности",rating:9.5,priority:"S",comfort:"Средний риск",description:"Большая sci-fi кампания с VR-first боем, исследованием и кастомизируемым оружием.",source:"https://www.uploadvr.com/top-25-best-meta-quest-3-games/",installWhere:"Quest 3 или ПК",qloader:"RUS"},
    {id:"curated-002",name:"Roboquest VR",category:"Экшен",subcategory:"Roguelite FPS",availability:"Meta + Steam",best:"Равно / по ситуации",platform:"Quest 3 + PCVR",bestRaw:"Quest 3 или PCVR",rating:9.5,priority:"S",multiplayer:"Да",comfort:"Высокий риск",description:"Очень быстрый roguelite-шутер с сильной VR-адаптацией и кооперативом.",source:"https://www.uploadvr.com/best-of-vr-2025-awards/",installWhere:"Quest 3 или ПК"},
    {id:"curated-003",name:"Skydance's BEHEMOTH",category:"Сюжет",subcategory:"Fantasy / ближний бой",availability:"Meta + Steam",best:"Steam лучше",platform:"Quest + PCVR",bestRaw:"PCVR для качества",rating:8.8,priority:"A",comfort:"Средний риск",description:"Крупное фэнтези-приключение с физическим оружием, масштабными существами и сюжетной кампанией.",source:"https://www.uploadvr.com/top-25-best-meta-quest-3-games/",installWhere:"Quest или ПК",qloader:"RUS"},
    {id:"curated-004",name:"Marvel's Deadpool VR",category:"Сюжет",subcategory:"Супергеройский экшен",availability:"Только Meta",best:"Meta лучше",platform:"Quest 3 / 3S",bestRaw:"Quest 3",rating:8.7,priority:"A",comfort:"Средний риск",description:"Крупная сюжетная VR-игра с фирменным юмором, стрельбой и ближним боем.",source:"https://www.uploadvr.com/marvels-deadpool-vr-review/",installWhere:"Quest 3"},
    {id:"curated-005",name:"Ghost Town",category:"Сюжет",subcategory:"Мистика / головоломки",availability:"Только Meta",best:"Meta лучше",platform:"Quest",bestRaw:"Quest 3",rating:9.3,priority:"S",comfort:"Низкий риск",description:"Сюжетное мистическое расследование от авторов The Room VR с сильной атмосферой и понятными головоломками.",source:"https://www.uploadvr.com/top-25-best-meta-quest-3-games/",installWhere:"Quest"},
    {id:"curated-006",name:"Puzzling Places",category:"Головоломка",subcategory:"3D-пазлы",availability:"Только Meta",best:"Meta лучше",platform:"Quest",bestRaw:"Quest",rating:9.2,priority:"S",story:"Нет",comfort:"Очень комфортно",description:"Медитативная сборка детализированных трёхмерных пазлов реальных мест и объектов.",installWhere:"Quest"},
    {id:"curated-007",name:"Cubism",category:"Головоломка",subcategory:"Пространственные пазлы / MR",availability:"Только Meta",best:"Meta лучше",platform:"Quest",bestRaw:"Quest / MR",rating:9.1,priority:"S",story:"Нет",comfort:"Очень комфортно",description:"Чистые пространственные головоломки руками; хорошо подходит для спокойного VR и mixed reality.",installWhere:"Quest"},
    {id:"curated-008",name:"Laser Dance",category:"Mixed Reality",subcategory:"MR / room-scale / уклонение",availability:"Только Meta",best:"Meta лучше",platform:"Quest 3 / 3S",bestRaw:"Quest 3 MR",rating:9.2,priority:"S",story:"Нет",comfort:"Низкий риск",description:"Комната превращается в полосу лазеров: нужно физически проходить, пригибаться и уклоняться в passthrough.",source:"https://www.uploadvr.com/top-25-best-meta-quest-3-games/",installWhere:"Quest 3"},
    {id:"curated-009",name:"Maestro",category:"Музыка",subcategory:"Дирижёр / hand tracking",availability:"Только Meta",best:"Meta лучше",platform:"Quest",bestRaw:"Quest / hand tracking",rating:9.0,priority:"S",story:"Нет",comfort:"Очень комфортно",description:"Музыкальная VR-игра, где руками дирижируешь оркестром; особенно хорошо демонстрирует hand tracking.",source:"https://www.uploadvr.com/top-25-best-meta-quest-3-games/",installWhere:"Quest"},
    {id:"curated-010",name:"Eye of the Temple",category:"Головоломка",subcategory:"Room-scale / приключение",availability:"Meta + Steam",best:"Meta лучше",platform:"Quest + PCVR",bestRaw:"Quest без кабеля",rating:9.2,priority:"S",comfort:"Низкий риск",description:"Физически перемещаешься по храму в своей игровой зоне; один из лучших примеров room-scale дизайна.",source:"https://www.uploadvr.com/top-25-best-meta-quest-3-games/",installWhere:"Quest или ПК"},
    {id:"curated-011",name:"Hotel Infinity",category:"Головоломка",subcategory:"Room-scale / невозможная геометрия",availability:"Только Meta",best:"Meta лучше",platform:"Quest",bestRaw:"Quest room-scale",rating:9.0,priority:"S",comfort:"Низкий риск",description:"Компактное физическое пространство превращается в большой невозможный отель за счёт clever room-scale дизайна.",source:"https://www.uploadvr.com/top-25-best-meta-quest-3-games/",installWhere:"Quest"},
    {id:"curated-012",name:"Demeo x Dungeons & Dragons: Battlemarked",category:"Настольные",subcategory:"Тактика / D&D / кооператив",availability:"Только Meta",best:"Meta лучше",platform:"Quest",bestRaw:"Quest",rating:9.1,priority:"S",multiplayer:"Да",comfort:"Очень комфортно",description:"Тактическая настольная RPG по D&D, рассчитанная на удобную одиночную или кооперативную игру в VR.",source:"https://www.uploadvr.com/top-25-best-meta-quest-3-games/",installWhere:"Quest"},
    {id:"curated-013",name:"Contractors Showdown",category:"Мультиплеер",subcategory:"Battle royale / extraction FPS",availability:"Только Meta",best:"Meta лучше",platform:"Quest",bestRaw:"Quest",rating:8.5,priority:"A",story:"Нет",multiplayer:"Да",comfort:"Высокий риск",description:"Крупномасштабный соревновательный VR-шутер от авторов Contractors.",installWhere:"Quest"},
    {id:"curated-014",name:"Pavlov Shack",category:"Мультиплеер",subcategory:"FPS / PvP",availability:"Только Meta",best:"Meta лучше",platform:"Quest",bestRaw:"Quest",rating:8.7,priority:"A",story:"Нет",multiplayer:"Да",comfort:"Высокий риск",description:"Standalone-версия классического Pavlov для Quest с соревновательными режимами и привычной VR-стрельбой.",installWhere:"Quest"},
    {id:"curated-015",name:"I Expect You To Die",category:"Головоломка",subcategory:"Шпионские escape-room задачи",availability:"Meta + Steam",best:"Meta лучше",platform:"Quest + PCVR",bestRaw:"Quest",rating:9.0,priority:"A",comfort:"Очень комфортно",description:"Сидячие шпионские головоломки с интерактивными механизмами и юмором; отличный комфортный VR.",installWhere:"Quest или ПК"},
    {id:"curated-016",name:"Star Wars: Tales from the Galaxy's Edge",category:"Сюжет",subcategory:"Star Wars / FPS / приключение",availability:"Только Meta",best:"Meta лучше",platform:"Quest",bestRaw:"Quest",rating:8.5,priority:"A",comfort:"Средний риск",description:"Полноценное приключение во вселенной Star Wars с перестрелками, персонажами и отдельными историями.",installWhere:"Quest"},
    {id:"curated-017",name:"Vader Immortal: Episode I",category:"Сюжет",subcategory:"Star Wars / приключение",availability:"Только Meta",best:"Meta лучше",platform:"Quest",bestRaw:"Quest",rating:8.6,priority:"A",comfort:"Низкий риск",description:"Кинематографичное первое знакомство с VR-Star Wars и световым мечом.",installWhere:"Quest"},
    {id:"curated-018",name:"Vader Immortal: Episode II",category:"Сюжет",subcategory:"Star Wars / приключение",availability:"Только Meta",best:"Meta лучше",platform:"Quest",bestRaw:"Quest",rating:8.3,priority:"B",comfort:"Низкий риск",description:"Продолжает историю и расширяет боевые возможности светового меча и Силы.",installWhere:"Quest"},
    {id:"curated-019",name:"Vader Immortal: Episode III",category:"Сюжет",subcategory:"Star Wars / приключение",availability:"Только Meta",best:"Meta лучше",platform:"Quest",bestRaw:"Quest",rating:8.5,priority:"A",comfort:"Низкий риск",description:"Финал трилогии Vader Immortal с более масштабными боями и завершением истории.",installWhere:"Quest"},
    {id:"curated-020",name:"Five Nights at Freddy's: Help Wanted",category:"Хоррор",subcategory:"Хоррор / мини-игры",availability:"Meta + Steam",best:"Meta лучше",platform:"Quest + PCVR",bestRaw:"Quest",rating:8.4,priority:"A",comfort:"Низкий риск",description:"Набор напряжённых VR-сцен и мини-игр FNAF; мало искусственного перемещения, но много скримеров.",installWhere:"Quest или ПК"},
    {id:"curated-021",name:"GORN",category:"Экшен",subcategory:"Физика / арена / ближний бой",availability:"Meta + Steam",best:"Meta лучше",platform:"Quest + PCVR",bestRaw:"Quest",rating:8.4,priority:"B",story:"Нет",comfort:"Средний риск",description:"Аркадная физическая арена с преувеличенным ближним боем; простая и очень VR-ориентированная.",installWhere:"Quest или ПК"},
    {id:"curated-022",name:"GORN 2",category:"Экшен",subcategory:"Физика / арена / ближний бой",availability:"Только Meta",best:"Meta лучше",platform:"Quest",bestRaw:"Quest",rating:8.6,priority:"A",story:"Нет",comfort:"Средний риск",description:"Более современное продолжение GORN с новыми аренами, противниками и физическими взаимодействиями.",installWhere:"Quest"},
    {id:"curated-023",name:"Gun Club VR",category:"Экшен",subcategory:"Тир / оружие",availability:"Meta + Steam",best:"Meta лучше",platform:"Quest + PCVR",bestRaw:"Quest",rating:8.5,priority:"A",story:"Нет",comfort:"Очень комфортно",description:"Большой виртуальный тир с множеством оружия, мишеней и сценариев без необходимости активно перемещаться.",installWhere:"Quest или ПК"},
    {id:"curated-024",name:"Little Cities",category:"Стратегия",subcategory:"Градостроитель",availability:"Только Meta",best:"Meta лучше",platform:"Quest",bestRaw:"Quest",rating:8.6,priority:"A",comfort:"Очень комфортно",description:"Уютный градостроитель вокруг виртуального стола; очень комфортен и хорошо читается в standalone VR.",installWhere:"Quest"},
    {id:"curated-025",name:"Max Mustard",category:"Сюжет",subcategory:"Платформер / третье лицо",availability:"Meta + Steam",best:"Meta лучше",platform:"Quest + PCVR",bestRaw:"Quest",rating:8.8,priority:"A",comfort:"Очень комфортно",description:"Красочный VR-платформер от третьего лица с большим количеством уровней и комфортной камерой.",installWhere:"Quest или ПК"},
    {id:"curated-026",name:"Vampire: The Masquerade - Justice",category:"Сюжет",subcategory:"Стелс / RPG / вампиры",availability:"Meta + Steam",best:"Steam лучше",platform:"Quest + PCVR",bestRaw:"PCVR для графики",rating:8.4,priority:"A",comfort:"Средний риск",description:"Сюжетный стелс-экшен во вселенной Vampire: The Masquerade с вампирскими способностями.",installWhere:"Quest или ПК"},
    {id:"curated-027",name:"The Climb",category:"Спорт",subcategory:"Скалолазание",availability:"Только Meta",best:"Meta лучше",platform:"Quest",bestRaw:"Quest",rating:8.3,priority:"B",story:"Нет",comfort:"Средний риск",description:"VR-скалолазание с красивыми маршрутами и физической работой руками.",installWhere:"Quest"},
    {id:"curated-028",name:"The Climb 2",category:"Спорт",subcategory:"Скалолазание",availability:"Только Meta",best:"Meta лучше",platform:"Quest",bestRaw:"Quest",rating:8.7,priority:"A",story:"Нет",comfort:"Средний риск",description:"Более разнообразное продолжение со скалами, городскими маршрутами и лучшей подачей.",installWhere:"Quest"}
  ].map(x => Object.assign({}, gameDefaults, x));

  const researchTier = [
    {id:"research-001",name:"Teenage Mutant Ninja Turtles: Empire City",category:"Сюжет",subcategory:"Beat 'em up / кооператив",availability:"Meta + Steam",best:"Равно / по ситуации",platform:"Quest 3 + PCVR",bestRaw:"Quest 3 или PCVR",rating:9.2,priority:"S",multiplayer:"Да",comfort:"Средний риск",description:"Сюжетный VR beat 'em up с одиночной игрой и кооперативом до четырёх игроков; сильная адаптация TMNT.",source:"https://roadtovr.com/teenage-mutant-ninja-turtles-vr-review-quest-pc-vr-pico/",installWhere:"Quest 3 или ПК"},
    {id:"research-002",name:"Reach",category:"Экшен",subcategory:"Паркур / приключение",availability:"Meta + Steam",best:"Steam лучше",platform:"Quest 3 + PCVR",bestRaw:"PCVR для качества",rating:8.8,priority:"A",comfort:"Высокий риск",description:"Амбициозное приключение с сильным упором на движение, лазание и физическую навигацию.",installWhere:"Quest 3 или ПК"},
    {id:"research-003",name:"Among Giants",category:"Сюжет",subcategory:"Атмосферное приключение",availability:"Только Meta",best:"Meta лучше",platform:"Quest 3",bestRaw:"Quest 3",rating:8.7,priority:"A",comfort:"Средний риск",description:"Крупное атмосферное приключение, рассчитанное именно на Quest 3.",installWhere:"Quest 3"},
    {id:"research-004",name:"Ancient Dungeon",category:"Экшен",subcategory:"Roguelite / dungeon crawler",availability:"Meta + Steam",best:"Равно / по ситуации",platform:"Quest + PCVR",bestRaw:"Quest или PCVR",rating:9.0,priority:"A",multiplayer:"Да",comfort:"Средний риск",description:"Процедурные подземелья, физический ближний бой, много улучшений и высокая реиграбельность; есть кооператив.",source:"https://www.uploadvr.com/meta-quests-horizon-monthly-games-may-2026/",installWhere:"Quest или ПК"},
    {id:"research-005",name:"Tetris Effect: Connected",category:"Головоломка",subcategory:"Tetris / музыка / визуал",availability:"Meta + Steam",best:"Meta лучше",platform:"Quest + PCVR",bestRaw:"Quest",rating:9.3,priority:"S",story:"Нет",comfort:"Очень комфортно",description:"Один из сильнейших спокойных VR-пазлов: классический Tetris соединён с музыкой, светом и погружающей подачей.",source:"https://www.uploadvr.com/best-puzzle-games-on-quest-in-2026/",installWhere:"Quest или ПК"},
    {id:"research-006",name:"The Room VR: A Dark Matter",category:"Головоломка",subcategory:"Escape room / мистика",availability:"Meta + Steam",best:"Meta лучше",platform:"Quest + PCVR",bestRaw:"Quest",rating:9.1,priority:"S",comfort:"Очень комфортно",description:"Премиальная серия пространственных головоломок с мистическим расследованием и сильной атмосферой.",installWhere:"Quest или ПК"},
    {id:"research-007",name:"Green Hell VR",category:"Survival",subcategory:"Выживание / джунгли",availability:"Meta + Steam",best:"Равно / по ситуации",platform:"Quest + PCVR",bestRaw:"Quest актуален; PCVR после обновлений",rating:8.7,priority:"A",multiplayer:"Да",comfort:"Высокий риск",description:"Глубокое выживание в джунглях с крафтом, ресурсами и кооперативом; проект продолжает получать обновления.",source:"https://www.uploadvr.com/green-hell-2026-roadmap-promises-major-pc-vr-update/",installWhere:"Quest или ПК"},
    {id:"research-008",name:"Population: ONE",category:"Мультиплеер",subcategory:"Battle royale / FPS",availability:"Только Meta",best:"Meta лучше",platform:"Quest",bestRaw:"Quest",rating:8.6,priority:"A",story:"Нет",multiplayer:"Да",comfort:"Высокий риск",basePrice:0,currentPrice:0,description:"Один из самых известных Quest multiplayer-шутеров: командные матчи, лазание и свободное перемещение по вертикали.",installWhere:"Quest"},
    {id:"research-009",name:"Creed: Rise to Glory",category:"Спорт",subcategory:"Бокс / фитнес",availability:"Meta + Steam",best:"Meta лучше",platform:"Quest + PCVR",bestRaw:"Quest",rating:8.5,priority:"A",story:"Есть",multiplayer:"Да",comfort:"Средний риск",description:"Кинематографичный VR-бокс с тренировками, кампанией и физической нагрузкой.",installWhere:"Quest или ПК"},
    {id:"research-010",name:"Action Hero",category:"Экшен",subcategory:"Кино / slow-motion action",availability:"Meta + Steam",best:"Meta лучше",platform:"Quest + PCVR",bestRaw:"Quest",rating:8.7,priority:"A",comfort:"Низкий риск",description:"Короткие кинематографичные экшен-сцены, где время реагирует на движения игрока; подходит для быстрых VR-сессий.",source:"https://www.uploadvr.com/great-on-steam-frame-vr-games-valve/",installWhere:"Quest или ПК"},
    {id:"research-011",name:"Vendetta Forever",category:"Экшен",subcategory:"Аркадный FPS / движение",availability:"Meta + Steam",best:"Meta лучше",platform:"Quest + PCVR",bestRaw:"Quest",rating:8.8,priority:"A",comfort:"Средний риск",description:"Очень VR-ориентированный аркадный экшен с короткими интенсивными сценами и необычной механикой перемещения через оружие.",installWhere:"Quest или ПК"},
    {id:"research-012",name:"Ghost Signal: A Stellaris Game",category:"Стратегия",subcategory:"Космос / roguelite",availability:"Meta + Steam",best:"Meta лучше",platform:"Quest + PCVR",bestRaw:"Quest",rating:8.8,priority:"A",comfort:"Очень комфортно",description:"Космический roguelite с управлением кораблём вокруг себя; хороший вариант для спокойной сидячей игры.",installWhere:"Quest или ПК"},
    {id:"research-013",name:"A Fisherman's Tale",category:"Головоломка",subcategory:"Нарративная головоломка",availability:"Meta + Steam",best:"Meta лучше",platform:"Quest + PCVR",bestRaw:"Quest",rating:8.8,priority:"A",comfort:"Очень комфортно",description:"Короткое, но очень изобретательное приключение с масштабом, перспективой и задачами, которые работают именно в VR.",installWhere:"Quest или ПК"},
    {id:"research-014",name:"The 7th Guest VR",category:"Головоломка",subcategory:"Мистика / escape room",availability:"Meta + Steam",best:"Steam лучше",platform:"Quest + PCVR",bestRaw:"PCVR для картинки",rating:8.7,priority:"A",comfort:"Низкий риск",description:"Большое мистическое приключение с объёмными персонажами и множеством головоломок в особняке.",installWhere:"Quest или ПК"},
    {id:"research-015",name:"Of Lies and Rain",category:"Сюжет",subcategory:"Sci-fi / приключение",availability:"Только Meta",best:"Meta лучше",platform:"Quest 3",bestRaw:"Quest 3",rating:8.6,priority:"A",comfort:"Средний риск",description:"Современное сюжетное sci-fi VR-приключение, выделенное профильными подборками среди заметных Quest-релизов.",installWhere:"Quest 3"}
  ].map(x => Object.assign({}, gameDefaults, x));

  const programs = [
    {id:"softplus-001",name:"HereSphere VR Video Player",category:"Видео",subcategory:"VR180 / 3D / продвинутый видеоплеер",platform:"Quest + Windows PC",rating:9.3,priority:"S",currentPrice:"Платно / есть demo",description:"Продвинутый плеер для VR/3D-видео с тонкой настройкой глубины, масштаба, резкости и воспроизведения.",source:"https://heresphere.com/",installWhere:"Quest или ПК"},
    {id:"softplus-002",name:"Wolvic Chromium",category:"Браузер",subcategory:"XR-браузер / Chromium",platform:"Quest",rating:9.0,priority:"S",currentPrice:"Бесплатно",description:"Альтернативный XR-браузер с актуальной Chromium-веткой, голосовым поиском и поддержкой Quest 3.",source:"https://www.wolvic.com/blog/release_1.9/",installWhere:"Quest"},
    {id:"softplus-003",name:"Quest Game Tuner",category:"Оптимизация",subcategory:"Разрешение / FPS / CPU-GPU / запись",platform:"Quest (APK)",rating:9.0,priority:"S",currentPrice:"$9.99",description:"Настраивает разрешение, FPS, foveation и производительность standalone-приложений; умеет профили, запись и OVR Metrics.",source:"https://threethan.itch.io/quest-game-tuner",installWhere:"Quest (APK)"},
    {id:"softplus-004",name:"Fluid",category:"Браузер",subcategory:"Продуктивность / многооконный Web",platform:"Quest",rating:8.8,priority:"A",currentPrice:"Бесплатно / freemium",description:"Многооконный spatial-браузер для работы и обычного Web в Quest; полезен как альтернатива системному браузеру.",installWhere:"Quest"},
    {id:"softplus-005",name:"DeoVR",category:"Видео",subcategory:"VR180 / 360 / spatial video",platform:"Quest + PCVR",rating:8.7,priority:"A",currentPrice:"Бесплатно / подписка по контенту",description:"Популярный VR-видеоплеер и платформа для VR180/360/spatial-видео; полезен как отдельный вариант рядом с SKYBOX/4XVR/HereSphere.",installWhere:"Quest или ПК"},
    {id:"softplus-006",name:"Immersed",category:"Удалённый рабочий стол",subcategory:"Виртуальные мониторы / работа",platform:"Quest + ПК",rating:8.6,priority:"A",currentPrice:"Бесплатно / подписка",description:"Рабочее пространство с виртуальными мониторами и подключением к компьютеру; имеет смысл для длинной работы в VR.",installWhere:"Quest + companion на ПК"},
    {id:"softplus-007",name:"QuestFiles VR File Manager",category:"Файлы",subcategory:"SMB / SFTP / WebDAV / Drive / USB",platform:"Quest",rating:9.1,priority:"S",currentPrice:"Платно",description:"Полноценный файловый менеджер: локальные файлы, NAS/SMB, FTP/SFTP, WebDAV, Google Drive, Dropbox, USB и архивы.",source:"https://www.meta.com/experiences/1162974433570137/",installWhere:"Quest"},
    {id:"softplus-008",name:"Meta Virtual Display",category:"Удалённый рабочий стол",subcategory:"До 3 виртуальных экранов / HDMI",platform:"Quest + Windows/Mac",rating:9.0,priority:"S",currentPrice:"Бесплатно / системно",description:"Системная функция Meta для подключения компьютера и вывода до трёх больших виртуальных экранов; в OS 2.7 заменила Remote Desktop и получила HDMI-ввод.",source:"https://www.meta.com/help/quest/172903867975450/",installWhere:"Quest / системная функция"},
    {id:"softplus-009",name:"Windows Mixed Reality Link",category:"Удалённый рабочий стол",subcategory:"Windows 11 / multi-monitor",platform:"Windows 11 + Quest 3/3S",rating:8.9,priority:"A",currentPrice:"Бесплатно",description:"Официальная связка Windows 11 с Quest 3/3S для быстрого приватного рабочего пространства с несколькими виртуальными мониторами.",source:"https://support.microsoft.com/en-us/windows/experience/compatibility/about-windows-mixed-reality-link",installWhere:"Windows 11"}
  ].map(x => Object.assign({}, programDefaults, x));

  const adults = [
    {id:"adult-001",name:"Captain Hardcore",subcategory:"Интерактивная VR/MR-песочница",availability:"Quest standalone + PCVR",platform:"Quest standalone / Steam PCVR",bestRaw:"Quest для passthrough; PCVR для графики",rating:9.0,priority:"S",comfort:"Средний риск",description:"Один из наиболее функциональных adult VR-проектов: самостоятельная Quest-версия, кастомизация, hand tracking и passthrough/MR.",source:"https://steamcommunity.com/app/1190600/discussions/0/801217116763137568/",installWhere:"Quest sideload или ПК"},
    {id:"adult-002",name:"VR HOT",subcategory:"VR/MR adult-симулятор",availability:"Quest standalone + PCVR",platform:"Quest standalone / Steam PCVR",bestRaw:"Quest для passthrough; PCVR по ситуации",rating:8.8,priority:"S",comfort:"Средний риск",description:"Отдельный VR/MR-проект с standalone Quest-версией и passthrough; Quest распространяется через sideload.",source:"https://www.vr-hot.com/faqs-for-quest",installWhere:"Quest sideload или ПК"},
    {id:"adult-003",name:"AFGirlfriend MR",subcategory:"MR-персонаж / passthrough",availability:"Quest standalone",platform:"Quest 3",bestRaw:"Quest 3 MR",rating:8.3,priority:"A",comfort:"Низкий риск",description:"MR-ориентированное приложение с виртуальным персонажем, использованием реальной комнаты и hand tracking.",installWhere:"Quest"},
    {id:"adult-004",name:"Pass Thru Hot Sauce",subcategory:"Mixed Reality / passthrough",availability:"Quest standalone",platform:"Quest 3",bestRaw:"Quest 3 MR",rating:8.2,priority:"A",comfort:"Низкий риск",description:"Узкоспециализированный MR-вариант с акцентом на размещение виртуального персонажа в реальном помещении через passthrough.",installWhere:"Quest"},
    {id:"adult-005",name:"XXXDIMENSION",subcategory:"Volumetric / MR",availability:"Quest / PCVR",platform:"Quest 3 + PCVR",bestRaw:"Quest 3 MR по ситуации",rating:8.3,priority:"A",comfort:"Низкий риск",description:"Отличается от обычного VR180 тем, что делает упор на объёмный volumetric-контент и mixed reality.",installWhere:"Quest или ПК"},
    {id:"adult-006",name:"EdenXVerse VR",subcategory:"VR-платформа / окружения",availability:"Quest / PCVR",platform:"VR",bestRaw:"По ситуации",rating:8.1,priority:"A",comfort:"Средний риск",description:"Расширяемая adult VR-платформа с несколькими окружениями и контентом; оставлена как отдельный тип сценария, а не одноразовая сцена.",installWhere:"VR"},
    {id:"adult-007",name:"Dezyred",subcategory:"Standalone / PCVR adult VR",availability:"Quest standalone + PCVR",platform:"Quest + PCVR",bestRaw:"Quest для автономности; PCVR по ситуации",rating:8.9,priority:"S",comfort:"Средний риск",description:"Сильная дополнительная альтернатива с native Quest-вариантом без обязательного ПК и отдельным PCVR-сценарием.",source:"https://bestadultvrgames.com/best-meta-quest-adult-games",installWhere:"Quest или ПК"},
    {id:"adult-008",name:"Virt-a-Mate + vamX",subcategory:"PCVR sandbox / модульная платформа",availability:"PCVR",platform:"Windows PCVR",bestRaw:"PCVR",rating:9.1,priority:"S",comfort:"Средний риск",description:"Глубокая модульная PCVR-песочница с большим количеством пользовательского контента; vamX добавляет готовый слой сценариев и управления.",source:"https://hub.virtamate.com/help/get_vam/",installWhere:"ПК / PCVR"},
    {id:"adult-009",name:"VR Paradise",subcategory:"PCVR adult experience",availability:"PCVR",platform:"Windows PCVR",bestRaw:"PCVR",rating:8.4,priority:"A",comfort:"Средний риск",description:"Известный PCVR-проект с большим объёмом готового контента; добавлен как отдельная PCVR-альтернатива, а не как серия мелких сцен.",source:"https://www.vrparadise.com/info",installWhere:"ПК / PCVR"}
  ].map(x => Object.assign({}, adultDefaults, x));

  window.BASE_DATA = (window.BASE_DATA || []).concat(acceptedMissing, researchTier, programs, adults);
})();
